### ISSUE TITLE
Line color

### ISSUE THREAD

**Issue by Fabian-Martinez-Rincon** [trinib/trinib#172]
Hello, I wanted to ask you how you made the separator line, since I wanted to change the colors

**Comment by trinib** [comment]
> 
> Hello, I wanted to ask you how you made the separator line, since I wanted to change the colors

you mean this https://camo.githubusercontent.com/6b68754bfe9a1bc4abebfabc34d4701bae4fa96c73172f2788d6a4163b0ce38c/68747470733a2f2f692e696d6775722e636f6d2f644261534b57462e676966 ?

**Comment by Fabian-Martinez-Rincon** [comment]
Yes

**Comment by trinib** [comment]
I did not made it. it is gif image I found
